### PR TITLE
tidying

### PR DESCRIPTION
**Pull request by tlr87**
Hello all :)

### CODE REVIEW

**Comment by anna-podhajska** [comment]
Hello Tom!
I am not sure if this is a bug at all, but there is no indentation on lines:
134, 143, 154, 166, 170.
Can u let me know when u push changes to it?
Cheerio : -D

**Comment by tlr87** [comment]
All corrected thanks so much :)

**Comment by anna-podhajska** [comment]
you're very good Tom!

**Comment by mike-keogh** [comment]
Hey Tom, I think the code would be a bit easier to read if the p elements were indented and closed as block level elements. Other than that its looking great!

**Pull request merged**
